services:
  - type: web
    name: rails-app
    env: ruby
    plan: free
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec rails s -b 0.0.0.0
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
      - key: RAILS_ENV
        value: production

databases:
  - name: postgres-db
    databaseName: rails_db
    user: rails_user
    plan: free
