default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: ecommerce_development

production:
  <<: *default
  host:     <%= Rails.application.credentials.dig(:database, :host) %>
  port:     5432
  database: postgres
  user:     postgres
  password: <%= Rails.application.credentials.dig(:database, :password) %>