default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ecommerce_development
  username: postgres
  password: postgres
  host: localhost

test:
  <<: *default
  database: ecommerce_test

production:
  <<: *default
  url: <%= Rails.application.credentials.dig(:supabase, :database_url) %>