default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ecommerce_development
  username: postgres
  password: postgres
  host: localhost

test:
  <<: *default
  database: ecommerce_test

production:
  <<: *default
  database: ecommerce_prod
  username: postgres
  password: postgres
  host: localhost